-- ============================================================
-- Base de datos: Inventario de Activos
-- Motor: PostgreSQL 11+ (usa EXECUTE FUNCTION en triggers)
-- ============================================================

-- ------------------------------------------------------------
-- 0. Crear la base de datos (ejecutar conectado a otra BD, ej. "postgres")
--    CREATE DATABASE no puede ejecutarse dentro de una transacción
-- ------------------------------------------------------------
CREATE DATABASE Zaico
  TEMPLATE template0
  ENCODING 'UTF8';

-- Conectarse a la nueva BD antes de continuar:
--   psql:     \c inventario_activos
--   pgAdmin:  abrir una ventana de consulta sobre inventario_activos

-- ------------------------------------------------------------
-- 1. Extensión pgcrypto (para hashear contraseñas en el seed)
--    Requiere privilegios de superusuario o de creación de extensiones
-- ------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ------------------------------------------------------------
-- 2. Función + triggers para Actualizado_el
--    (equivalente a ON UPDATE CURRENT_TIMESTAMP de MySQL)
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_touch_actualizado_el()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$ BEGIN
  NEW.Actualizado_el := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
 $$;

-- ------------------------------------------------------------
-- 3. USUARIOS
-- ------------------------------------------------------------
CREATE TABLE USUARIOS (
  id             INT          GENERATED BY DEFAULT AS IDENTITY,
  Nombre         VARCHAR(100) NOT NULL,
  Contrasena     VARCHAR(255) NOT NULL,
  f              INT          NULL,
  Creado_el      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Actualizado_el TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Estado         SMALLINT     NOT NULL DEFAULT 1,
  CONSTRAINT pk_usuarios PRIMARY KEY (id),
  CONSTRAINT ck_usuarios_estado CHECK (Estado IN (0, 1))
);

COMMENT ON COLUMN USUARIOS.Contrasena IS 'Almacenar hash (bcrypt/argon2), nunca texto plano';
COMMENT ON COLUMN USUARIOS.f IS 'Campo heredado del diagrama original; verificar propósito';

CREATE TRIGGER trg_usuarios_touch
  BEFORE UPDATE ON USUARIOS
  FOR EACH ROW EXECUTE FUNCTION fn_touch_actualizado_el();

-- ------------------------------------------------------------
-- 4. ROLES  (sin fk_permisos: sin relación circular)
-- ------------------------------------------------------------
CREATE TABLE ROLES (
  id         INT         GENERATED BY DEFAULT AS IDENTITY,
  Nombre_rol VARCHAR(50) NOT NULL,
  Estado     SMALLINT    NOT NULL DEFAULT 1,
  CONSTRAINT pk_roles PRIMARY KEY (id),
  CONSTRAINT uq_roles_nombre UNIQUE (Nombre_rol),
  CONSTRAINT ck_roles_estado CHECK (Estado IN (0, 1))
);

-- ------------------------------------------------------------
-- 5. PERMISOS
-- ------------------------------------------------------------
CREATE TABLE PERMISOS (
  id             INT          GENERATED BY DEFAULT AS IDENTITY,
  Nombre_permiso VARCHAR(100) NOT NULL,
  Estado         VARCHAR(20)  NOT NULL DEFAULT 'Activo',
  CONSTRAINT pk_permisos PRIMARY KEY (id),
  CONSTRAINT uq_permisos_nombre UNIQUE (Nombre_permiso)
);

-- ------------------------------------------------------------
-- 6. ROL_USUARIOS  (único puente entre USUARIOS y ROLES)
-- ------------------------------------------------------------
CREATE TABLE ROL_USUARIOS (
  id         INT GENERATED BY DEFAULT AS IDENTITY,
  fk_rol     INT NOT NULL,
  fk_Usuario INT NOT NULL,
  CONSTRAINT pk_rolusuarios PRIMARY KEY (id),
  CONSTRAINT uq_rolusuarios UNIQUE (fk_rol, fk_Usuario),
  CONSTRAINT fk_rolusuarios_rol
    FOREIGN KEY (fk_rol) REFERENCES ROLES (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_rolusuarios_usuario
    FOREIGN KEY (fk_Usuario) REFERENCES USUARIOS (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_rolusuarios_usuario ON ROL_USUARIOS (fk_Usuario);

-- ------------------------------------------------------------
-- 7. PERMISOS_ROL  (único puente entre ROLES y PERMISOS)
-- ------------------------------------------------------------
CREATE TABLE PERMISOS_ROL (
  id         INT GENERATED BY DEFAULT AS IDENTITY,
  fk_rol     INT NOT NULL,
  fk_permiso INT NOT NULL,
  CONSTRAINT pk_permisosrol PRIMARY KEY (id),
  CONSTRAINT uq_permisosrol UNIQUE (fk_rol, fk_permiso),
  CONSTRAINT fk_permisosrol_rol
    FOREIGN KEY (fk_rol) REFERENCES ROLES (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_permisosrol_permiso
    FOREIGN KEY (fk_permiso) REFERENCES PERMISOS (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_permisosrol_permiso ON PERMISOS_ROL (fk_permiso);

-- ------------------------------------------------------------
-- 8. PERSONAL
-- ------------------------------------------------------------
CREATE TABLE PERSONAL (
  id             INT          GENERATED BY DEFAULT AS IDENTITY,
  Nombre         VARCHAR(100) NOT NULL,
  Apellido       VARCHAR(100) NOT NULL,
  Nombre_usuario VARCHAR(50)  NOT NULL,
  Cargo          VARCHAR(100) NULL,
  Observaciones  TEXT         NULL,
  Estado         VARCHAR(20)  NOT NULL DEFAULT 'Activo',
  CONSTRAINT pk_personal PRIMARY KEY (id),
  CONSTRAINT uq_personal_nombre_usuario UNIQUE (Nombre_usuario)
);

-- ------------------------------------------------------------
-- 9. ACTIVOS
-- ------------------------------------------------------------
CREATE TABLE ACTIVOS (
  id                       INT          GENERATED BY DEFAULT AS IDENTITY,
  Nombre_de_activo         VARCHAR(150) NOT NULL,
  Ubicacion                VARCHAR(150) NULL,
  Ubicacion_Predeterminada VARCHAR(150) NULL,
  Serial                   VARCHAR(100) NULL,
  Fabricante               VARCHAR(100) NULL,
  Categoria                VARCHAR(100) NULL,
  Modelo                   VARCHAR(100) NULL,
  Creado_el                TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Actualizado_el           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Observaciones            TEXT         NULL,
  Etiqueta_activo          VARCHAR(100) NULL,
  Estado                   VARCHAR(20)  NOT NULL DEFAULT 'Activo',
  Direccion_MAC            VARCHAR(17)  NULL,
  Imagen_Activo            VARCHAR(255) NULL,
  CONSTRAINT pk_activos PRIMARY KEY (id),
  CONSTRAINT uq_activos_serial UNIQUE (Serial),
  CONSTRAINT uq_activos_etiqueta UNIQUE (Etiqueta_activo)
);

COMMENT ON COLUMN ACTIVOS.Imagen_Activo IS 'Ruta o nombre del archivo de imagen';

CREATE TRIGGER trg_activos_touch
  BEFORE UPDATE ON ACTIVOS
  FOR EACH ROW EXECUTE FUNCTION fn_touch_actualizado_el();

-- ------------------------------------------------------------
-- 10. COMPRAS  (relación 1:0..1 con ACTIVOS vía fk_activo UNIQUE)
-- ------------------------------------------------------------
CREATE TABLE COMPRAS (
  id                 INT           GENERATED BY DEFAULT AS IDENTITY,
  fk_activo          INT           NOT NULL,
  Numero_Requisicion VARCHAR(50)   NULL,
  Fecha_Compra       DATE          NULL,
  Proveedor          VARCHAR(150)  NULL,
  Costo_compra       NUMERIC(12,2) NULL,
  Tiempo_garantia    VARCHAR(50)   NULL,
  Imagen_Factura     VARCHAR(255)  NULL,
  Garantia           VARCHAR(50)   NULL,
  Numero_factura     VARCHAR(50)   NULL,
  CONSTRAINT pk_compras PRIMARY KEY (id),
  CONSTRAINT uq_compras_activo UNIQUE (fk_activo),
  CONSTRAINT fk_compras_activo
    FOREIGN KEY (fk_activo) REFERENCES ACTIVOS (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- ------------------------------------------------------------
-- 11. ASIGNACIONES
-- ------------------------------------------------------------
CREATE TABLE ASIGNACIONES (
  id               INT  GENERATED BY DEFAULT AS IDENTITY,
  fk_Activo        INT  NOT NULL,
  fk_Personal      INT  NOT NULL,
  fk_Usuario       INT  NOT NULL,
  Fecha_asignacion DATE NOT NULL,
  CONSTRAINT pk_asignaciones PRIMARY KEY (id),
  CONSTRAINT fk_asignaciones_activo
    FOREIGN KEY (fk_Activo) REFERENCES ACTIVOS (id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_asignaciones_personal
    FOREIGN KEY (fk_Personal) REFERENCES PERSONAL (id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_asignaciones_usuario
    FOREIGN KEY (fk_Usuario) REFERENCES USUARIOS (id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_asignaciones_activo   ON ASIGNACIONES (fk_Activo);
CREATE INDEX idx_asignaciones_personal ON ASIGNACIONES (fk_Personal);
CREATE INDEX idx_asignaciones_usuario  ON ASIGNACIONES (fk_Usuario);